version: '3.8'

services:
  php:
    build: .
    container_name: php
    volumes:
      - ./board_login:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./board_login:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: board_login
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  db_nopass:
    image: mysql:8.0
    container_name: db_nopass
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_nopass
    ports:
      - "3307:3306"
    volumes:
      - ./board_login/250531/board_nopass.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data-nopass:/var/lib/mysql


  db_pass:
    image: mysql:8.0
    container_name: db_pass
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_pass
    ports:
      - "3308:3306"
    volumes:
      - ./board_login/250531/board_pass.sql:/docker-entrypoint-initdb.d/init.sql
      - db-pass-data:/var/lib/mysql

volumes:
  db-data:
  db-data-nopass:
  db-pass-data: